version: '3.6'
services:
  talkeat-be:
    image: prueba-be
    ports:
    - "80:80"
    environment:
    - NODE_ENV=production
    networks:
      - internal
  mongodb:
    image: mongo
    volumes:
    - /opt/mongodb:/data/db
    networks:
    - internal
networks:
  internal:
    external: false
